#!/usr/bin/env python3
"""grid.py: step 7's timing (NOTES.md): grid:K, K copies of pile200 side by side (scene.c's build_grid), sleep off, on the
twin at 1 and 8 threads and on every GPU, F and V4, from toy.c's cost lines (per tick over ticks 2 to N: the wall, the
kernels per stage from timestamps, the CPU stages, the uploads and readbacks). Cost only: how the tick scales with the
body count, and how much of it is dispatch overhead. Writes the tables to lab/gpu/toy/results/grid.md.

  python lab/gpu/toy/grid.py [--ks 1,4,16,64] [--ticks 300] [--compiler msvc] [--gpus 0xff] [--out lab/gpu/build/toy-scratch/grid]
                             [--no-run]

Each run also compares every tick's hashes on every GPU with the twin's (the same run at scale).
"""
import argparse
import os
import re
import subprocess
import sys

TOY = os.path.dirname(os.path.abspath(__file__))
LAB = os.path.dirname(TOY)
EXE = ".exe" if sys.platform == "win32" else ""
GROUPS = [("narrowphase", ("narrowSat", "narrowClip", "copyManifolds")),
          ("prepare", ("prepareBodies", "prepareContacts", "prepareJoints")),
          ("solve", ("warmStart", "pushContacts", "relaxContacts", "restitution", "storeImpulses", "warmStartJoints", "solveJoints",
                     "relaxJoints")),
          ("bodies", ("integrateVelocities", "integratePositions", "finalizeBodies", "wakeBodies")),
          ("hashes", ("hashElements", "hashManifolds", "hashJoints"))]
COLOUR_STAGES = ("warmStart", "pushContacts", "relaxContacts")  # the per-colour dispatches


def parse(text):
    out = {}
    for m in re.finditer(r"^cost (\S+): (.*?) \|(.*)$", text, re.M):
        who, head, tail = m.groups()
        v = dict(zip(head.split()[0::2], (float(x) for x in head.split()[1::2])))
        stages = {}
        t = tail.split()
        for i in range(0, len(t), 3):
            stages[t[i]] = (float(t[i + 1]), float(t[i + 2]))
        v["stages"] = stages
        out[who] = v
    gpus = dict(re.findall(r"^gpu (\d+): (.*?) \(", text, re.M))
    same = {f"gpu{g}": verdict.startswith("identical") for g, _, verdict in
            re.findall(r"^gpu (\d+) (\w+): per-tick hashes (identical to the twin's|DIFFER from the twin's)", text, re.M)}
    return out, gpus, same


def run(a):
    os.makedirs(a.out, exist_ok=True)
    for k in a.ks:
        for d in ("F", "V4"):
            log = os.path.join(a.out, f"grid{k}.{d}.txt")
            exe = os.path.join(LAB, "build", a.compiler, "bin", f"toy_{d}{EXE}")
            args = [exe, "--scene", f"grid:{k}", "--sleep", "0", "--ticks", str(a.ticks), "--threads", "1,8", "--gpus", a.gpus, "--quiet",
                    "--log", log]
            r = subprocess.run(args, cwd=LAB, capture_output=True, text=True)
            print(f"grid:{k} {d}: exit {r.returncode}" + (f" {r.stderr.strip()[:200]}" if r.returncode else ""), flush=True)


def fmt(x, d=3):
    return "-" if x is None else f"{x:.{d}g}" if abs(x) < 1000 else f"{x:.0f}"


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--ks", default="1,4,16,64")
    p.add_argument("--ticks", type=int, default=300)
    p.add_argument("--compiler", default="msvc")
    p.add_argument("--gpus", default="0xff")
    p.add_argument("--out", default=os.path.join(LAB, "build", "toy-scratch", "grid"))
    p.add_argument("--no-run", action="store_true")
    p.add_argument("--md", default=os.path.join(TOY, "results", "grid.md"))
    a = p.parse_args()
    a.ks = [int(x) for x in a.ks.split(",")]
    a.out = os.path.abspath(a.out)
    if not a.no_run:
        run(a)
    R = {}  # (k, d) -> (costs by who, gpu names, gpu same)
    for k in a.ks:
        for d in ("F", "V4"):
            log = os.path.join(a.out, f"grid{k}.{d}.txt")
            if os.path.exists(log):
                R[(k, d)] = parse(open(log, errors="replace").read())
    whos = []
    names = {}
    for (k, d), (c, g, _) in R.items():
        for w in c:
            if w not in whos:
                whos.append(w)
        names.update({f"gpu{i}": n for i, n in g.items()})
    whos.sort(key=lambda w: (w.startswith("gpu"), w))
    label = {w: (names.get(w, w) if w.startswith("gpu") else f"twin, {w[4:]} thread{'s' if w[4:] != '1' else ''}") for w in whos}

    lines = ["# Step 7: grid:K timing", "",
             f"Generated by `lab/gpu/toy/grid.py` ({a.compiler} twins; {a.ticks} ticks, the costs averaged per tick over ticks 2 to "
             f"{a.ticks}: tick 1 warms the drivers up). grid:K is K copies of pile200 (the same draws: 200 bodies falling into a "
             "pit) 6.5 m apart on one floor, sleep off, so every body is solved every tick. Cost only (NOTES.md, step 7).", "",
             "Reproduce (Windows, from the repository's root):", "", "```",
             "python lab/gpu/toy/gen_toy.py && python lab/gpu/lab.py build --compiler msvc",
             f"python lab/gpu/toy/grid.py --ticks {a.ticks}      # logs in lab/gpu/build/toy-scratch/grid", "```", ""]
    # bit-exactness at scale
    ok = []
    for (k, d), (c, g, same) in sorted(R.items()):
        ok.append(f"grid:{k} {d}: " + ", ".join(f"{label[w]} {'identical' if s else 'DIFFERS'}" for w, s in sorted(same.items())))
    lines += ["Every tick's hashes on the GPUs against the twin's (the same run at scale):", ""] + [f"- {x}" for x in ok] + [""]

    # the main table: per K, dialect and machine
    lines += ["## Per tick (ms)", "",
              "wall: the tick end to end (the GPUs: two submits, the readbacks, the CPU stages; the twin: its dispatches and stages); "
              "kernels: the dispatches' sum (GPUs: timestamps after every dispatch, each followed by a full barrier); cpu: the CPU "
              "stages (broadphase, islands, colouring, the lists); up/read: the GPUs' uploads before the dispatches and readbacks "
              "after them, from timestamps; then the kernels by stage, and the solve's cost per colour dispatch (warm start, push "
              "and relax: one dispatch per colour per substep).", "",
              "| K | bodies | pairs (active) | colours | dialect | machine | dispatches | wall | kernels | cpu | up / read | narrowphase "
              "| prepare | solve | bodies | hashes | solve per colour dispatch (us) |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for k in a.ks:
        for d in ("F", "V4"):
            if (k, d) not in R:
                continue
            c = R[(k, d)][0]
            for w in whos:
                if w not in c:
                    continue
                v = c[w]
                st = v["stages"]
                grp = [sum(st.get(e, (0, 0))[0] for e in es) for _, es in GROUPS]
                cms = sum(st.get(e, (0, 0))[0] for e in COLOUR_STAGES)
                cnt = sum(st.get(e, (0, 0))[1] for e in COLOUR_STAGES)
                per = 1000 * cms / cnt if cnt else None
                lines.append(f"| {k} | {v['bodies']:.0f} | {v['pairs']:.0f} ({v['active']:.0f}) | {v['colours']:.1f} | {d} | {label[w]} | "
                             f"{v['dispatches']:.0f} | {fmt(v['wall'])} | {fmt(v['kernels'])} | {fmt(v['cpu'])} | "
                             f"{fmt(v['upload'], 2)} / {fmt(v['readback'], 2)} | " + " | ".join(fmt(x) for x in grp) + f" | {fmt(per)} |")
    lines.append("")

    # scaling and the dispatch overhead. The dispatch count hardly moves with K (about 220 to 250: the colours do not grow),
    # so a fit of kernels = a dispatches + b bodies is ill-conditioned; instead the work per body is the kernels' slope
    # between the two largest K (the machine is busy there), and what remains at each K once that work is taken out is the
    # fixed cost: launches, barriers, a GPU too empty to fill.
    lines += ["## Scaling and dispatch overhead", "",
              "Per machine and dialect: the tick at each K against K = 1 (the bodies grow K times, the dispatches hardly at all); "
              "the work per body, the kernels' slope between the two largest K; the fixed cost, the kernels' time at each K less "
              "that work, and its share of the kernels' time (on the twin at one thread there is no barrier, and the fixed cost "
              "is within the noise); and the kernels' time per dispatch at K = 1, where the GPUs are nearly empty.", "",
              "| dialect | machine | wall at K = " + " / ".join(str(k) for k in a.ks) + " (x of K = 1) | kernels (x) | work per "
              "body (us) | kernels per dispatch at K = 1 (us) | fixed cost at K = " + " / ".join(str(k) for k in a.ks) +
              " (ms, share of the kernels) |", "|---|---|---|---|---|---|---|"]
    for d in ("F", "V4"):
        for w in whos:
            pts = [(k, R[(k, d)][0][w]) for k in a.ks if (k, d) in R and w in R[(k, d)][0]]
            if len(pts) < 2:
                continue
            (_, u), (_, v) = pts[-2], pts[-1]
            work = (v["kernels"] - u["kernels"]) / (v["bodies"] - u["bodies"])
            w1, k1 = pts[0][1]["wall"], pts[0][1]["kernels"]
            fixed = [(x["kernels"] - work * x["bodies"]) for _, x in pts]
            lines.append(f"| {d} | {label[w]} | " + " / ".join(f"{fmt(x['wall'])} ({x['wall'] / w1:.2g}x)" for _, x in pts) + " | " +
                         " / ".join(f"{fmt(x['kernels'])} ({x['kernels'] / k1:.2g}x)" for _, x in pts) + f" | {fmt(work * 1000)} | "
                         f"{fmt(1000 * k1 / pts[0][1]['dispatches'])} | " +
                         " / ".join(f"{fmt(f, 2)} ({100 * f / x['kernels']:.0f}%)" for f, (_, x) in zip(fixed, pts)) + " |")
    lines.append("")
    # where the GPUs' wall goes
    lines += ["## Where a GPU's tick goes (ms per tick)", "",
              "wall = kernels + CPU stages + uploads + readbacks + the rest (two submits and their waits, the host's copies, the "
              "driver).", "",
              "| dialect | machine | K | wall | kernels | CPU stages | uploads | readbacks | the rest |", "|---|---|---|---|---|---|---|---|---|"]
    for d in ("F", "V4"):
        for w in whos:
            if not w.startswith("gpu"):
                continue
            for k in a.ks:
                if (k, d) not in R or w not in R[(k, d)][0]:
                    continue
                x = R[(k, d)][0][w]
                rest = x["wall"] - x["kernels"] - x["cpu"] - x["upload"] - x["readback"]
                lines.append(f"| {d} | {label[w]} | {k} | {fmt(x['wall'])} | {fmt(x['kernels'])} | {fmt(x['cpu'])} | {fmt(x['upload'], 2)} | "
                             f"{fmt(x['readback'], 2)} | {fmt(rest, 2)} |")
    lines.append("")
    md = "\n".join(lines)
    os.makedirs(os.path.dirname(a.md), exist_ok=True)
    with open(a.md, "w", newline="\n") as f:
        f.write(md)
    print(md)
    print(f"\nwritten {a.md}")


if __name__ == "__main__":
    main()
